[package]
name = "contracts"
version = "1.0.0"
authors = []

[addresses]
contracts = "0x25a289ce0548eddf0d05dca45464d5eafc934a8a4f13a2b133bf723d7b8559eb"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "e85553104911152d800fa2c32f7ef0d80daf60b9"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
