[package]
name = "contracts"
version = "1.0.0"
authors = []

[addresses]
contracts = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement-v1.0.0-rc1"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
